-- Run this in Supabase SQL Editor AFTER creating your account in the app.
-- Replace 'YOUR_USER_ID_HERE' with your actual user ID from Auth > Users in the Supabase dashboard.

INSERT INTO applications (user_id, company, role, status, date, source, notes) VALUES
('YOUR_USER_ID_HERE', 'Ascenda', 'Technical Operations Engineer (Software Ops)', 'applied', '2026-05-05', 'Direct', 'Application confirmation received.'),
('YOUR_USER_ID_HERE', 'Adyen', 'Technical Support Engineer', 'rejected', '2026-03-12', 'Recruiter (Mac Zhou)', 'Missed skills interview 31 Mar. Rejected 1 May.'),
('YOUR_USER_ID_HERE', 'Wise', 'Technical Support Engineer (Enterprise)', 'rejected', '2026-04-09', 'Direct', 'Video interview 23 Apr. Did not proceed 27 Apr.'),
('YOUR_USER_ID_HERE', 'Solace', '(role not specified)', 'applied', '2026-04-03', 'LinkedIn', 'LinkedIn Easy Apply.'),
('YOUR_USER_ID_HERE', 'OpenAI', 'AI Support Engineer', 'rejected', '2026-04-01', 'Direct', 'Rejected 1 Apr 2026.'),
('YOUR_USER_ID_HERE', 'FairPrice Group', 'Automation Engineer (WES/WCS)', 'applied', '2026-03-19', 'LinkedIn', 'LinkedIn Easy Apply.'),
('YOUR_USER_ID_HERE', 'TikTok', 'Technical Data Analyst - Trust & Safety', 'applied', '2026-03-10', 'LinkedIn', 'LinkedIn Easy Apply.'),
('YOUR_USER_ID_HERE', 'TikTok', 'Workflow Management Analyst - Trust & Safety', 'applied', '2026-03-10', 'LinkedIn', 'LinkedIn Easy Apply.'),
('YOUR_USER_ID_HERE', 'SmartStream', 'Application Support Analyst', 'rejected', '2026-03-02', 'Direct', 'Rejected by hr@smartstream-stp.com.'),
('YOUR_USER_ID_HERE', 'Bank of America', 'Application Production Services Specialist', 'applied', '2026-03-02', 'Argyll Scott (Mani Sharma)', 'Right to represent confirmed 2 Mar.'),
('YOUR_USER_ID_HERE', 'Dexian', 'Platform Engineer (OpenShift)', 'applied', '2026-02-26', 'LinkedIn', ''),
('YOUR_USER_ID_HERE', 'Viasat', 'Site Reliability Engineer', 'applied', '2026-02-26', 'LinkedIn', ''),
('YOUR_USER_ID_HERE', 'TikTok', 'Platform User Operations Specialist', 'rejected', '2026-02-23', 'LinkedIn', 'Rejected 25 Feb via careers portal.'),
('YOUR_USER_ID_HERE', 'Etiqa Insurance', '(role not specified)', 'applied', '2026-02-23', 'LinkedIn', ''),
('YOUR_USER_ID_HERE', 'Luxoft Singapore', '(role not specified)', 'applied', '2026-02-23', 'LinkedIn', 'Application viewed.'),
('YOUR_USER_ID_HERE', 'PALO IT', '(role not specified)', 'applied', '2026-02-23', 'LinkedIn', 'Application viewed.'),
('YOUR_USER_ID_HERE', 'SimplyGo', '(role not specified)', 'applied', '2026-02-23', 'LinkedIn', ''),
('YOUR_USER_ID_HERE', 'Quess Singapore', '(role not specified)', 'applied', '2026-02-23', 'LinkedIn', ''),
('YOUR_USER_ID_HERE', 'Transmedic Group', '(role not specified)', 'applied', '2026-02-23', 'LinkedIn', ''),
('YOUR_USER_ID_HERE', 'Neurones IT Asia', 'Application Support Analyst', 'applied', '2026-02-23', 'LinkedIn', ''),
('YOUR_USER_ID_HERE', 'Samsung Re', 'Application & Database Support Analyst', 'applied', '2026-02-23', 'LinkedIn', ''),
('YOUR_USER_ID_HERE', 'Unit21', 'Technical Support Specialist', 'applied', '2026-02-18', 'Direct', 'Application acknowledgement received.'),
('YOUR_USER_ID_HERE', 'Hudson Singapore', '(role not specified)', 'applied', '2026-02-15', 'LinkedIn', ''),
('YOUR_USER_ID_HERE', 'Evooq', 'Application Support Engineer', 'applied', '2026-02-13', 'LinkedIn', 'Application confirmation received Feb 2026.'),
('YOUR_USER_ID_HERE', 'Optimum Solutions', '(role not specified)', 'applied', '2026-02-10', 'LinkedIn', ''),
('YOUR_USER_ID_HERE', 'AvePoint', '(role not specified)', 'applied', '2026-02-10', 'LinkedIn', ''),
('YOUR_USER_ID_HERE', 'Sygnia', '(role not specified)', 'rejected', '2026-02-09', 'Direct', 'Video interview with Adi 11 Feb. Rejected.'),
('YOUR_USER_ID_HERE', 'Partior', '(role not specified)', 'applied', '2026-02-09', 'LinkedIn', ''),
('YOUR_USER_ID_HERE', 'Smart IMS Inc.', '(role not specified)', 'applied', '2026-02-09', 'LinkedIn', ''),
('YOUR_USER_ID_HERE', 'PDR Group', '(role not specified)', 'applied', '2026-02-09', 'LinkedIn', 'Application viewed.'),
('YOUR_USER_ID_HERE', 'InfoCepts', 'Junior Cloud & Infra Engineer', 'applied', '2026-02-08', 'LinkedIn', ''),
('YOUR_USER_ID_HERE', 'Astreya', '(role not specified)', 'applied', '2026-02-06', 'LinkedIn', ''),
('YOUR_USER_ID_HERE', 'Nicoll Curtin', 'Intelligence Process Automation Specialist', 'applied', '2026-02-05', 'LinkedIn', ''),
('YOUR_USER_ID_HERE', 'Applicantz', 'Jr. Software Engineer', 'in_progress', '2025-12-23', 'LinkedIn', 'Received coding test 5 Jan 2026. Submitted. No update since.'),
('YOUR_USER_ID_HERE', 'Stripe', 'Integration Reliability Engineer, Technical Operations', 'rejected', '2025-12-01', 'Direct', 'Rejected 13 Jan 2026.'),
('YOUR_USER_ID_HERE', 'Rakuten', 'Associate Engineer, Backend', 'rejected', '2025-11-14', 'Direct', 'Rejected 3 Jan 2026.'),
('YOUR_USER_ID_HERE', 'Carta', '(role not specified)', 'applied', '2026-01-07', 'Direct', 'Application confirmation received 7 Jan.'),
('YOUR_USER_ID_HERE', 'Ashby', 'Product Support Specialist (APAC)', 'applied', '2026-01-06', 'Direct', 'Application confirmation received 6 Jan.'),
('YOUR_USER_ID_HERE', 'SMRT', 'Executive, System Integration & Support', 'applied', '2026-01-06', 'Direct', 'Application via SMRT Career Portal.'),
('YOUR_USER_ID_HERE', 'Assurity Trusted Solutions', 'Software Engineer (ServiceNow)', 'applied', '2025-12-23', 'LinkedIn', 'Application submitted via Workable.'),
('YOUR_USER_ID_HERE', 'Kris Infotech', '(role not specified)', 'applied', '2025-12-23', 'LinkedIn', ''),
('YOUR_USER_ID_HERE', 'Ministry of Social and Family Development', '(role not specified)', 'applied', '2025-12-23', 'LinkedIn', ''),
('YOUR_USER_ID_HERE', 'ABN AMRO Clearing Bank', '(role not specified)', 'applied', '2025-12-23', 'LinkedIn', ''),
('YOUR_USER_ID_HERE', 'HCLTech', '(role not specified)', 'applied', '2025-12-23', 'LinkedIn', ''),
('YOUR_USER_ID_HERE', 'NCS Group', 'Software Engineer', 'applied', '2025-12-21', 'Direct', 'Confirmation from SmartRecruiters.'),
('YOUR_USER_ID_HERE', 'Nityo Infotech', 'Junior Java Developer', 'applied', '2025-12-21', 'LinkedIn', ''),
('YOUR_USER_ID_HERE', 'Manpower Singapore', '(role not specified)', 'applied', '2025-12-21', 'LinkedIn', 'Multiple applications.'),
('YOUR_USER_ID_HERE', 'Unison Group', 'Web Automation Test Engineer', 'applied', '2025-12-21', 'Direct', 'Application submitted via Workable.'),
('YOUR_USER_ID_HERE', 'Evolution Singapore', 'Business/Functional Analyst (1-yr contract)', 'applied', '2025-12-21', 'LinkedIn', ''),
('YOUR_USER_ID_HERE', 'TDCX', '(role not specified)', 'applied', '2025-12-19', 'LinkedIn', ''),
('YOUR_USER_ID_HERE', 'Maltem Asia-Pacific', '(role not specified)', 'applied', '2025-12-19', 'LinkedIn', ''),
('YOUR_USER_ID_HERE', 'Foodpanda', 'Backend Software Engineer I', 'applied', '2025-12-19', 'LinkedIn', 'Confirmation from Delivery Hero group.'),
('YOUR_USER_ID_HERE', 'Capgemini', 'Junior Data Analyst', 'applied', '2025-12-19', 'LinkedIn', ''),
('YOUR_USER_ID_HERE', 'AIA Singapore', '(role not specified)', 'applied', '2025-12-19', 'LinkedIn', ''),
('YOUR_USER_ID_HERE', 'Genpact', '(role not specified)', 'applied', '2025-12-19', 'LinkedIn', ''),
('YOUR_USER_ID_HERE', 'Exasoft', '(role not specified)', 'applied', '2025-12-19', 'LinkedIn', ''),
('YOUR_USER_ID_HERE', 'Orexe', '(role not specified)', 'applied', '2025-12-19', 'LinkedIn', ''),
('YOUR_USER_ID_HERE', 'Luxoft Singapore', 'Junior DevOps Platform Engineer', 'in_progress', '2025-12-19', 'LinkedIn', 'Screened by Grace Chan (DXC/Luxoft) 19 Dec. Provided details. No further update.'),
('YOUR_USER_ID_HERE', 'Randstad', 'Data Analyst (Telco/Banking/Fintech)', 'applied', '2025-12-19', 'Randstad', ''),
('YOUR_USER_ID_HERE', 'Randstad', 'IT Support Specialist (Financial Services)', 'applied', '2025-12-19', 'Randstad', ''),
('YOUR_USER_ID_HERE', 'Randstad', 'QA Engineer (Selenium/Java/TestNG)', 'applied', '2025-12-19', 'Randstad', ''),
('YOUR_USER_ID_HERE', 'Randstad', 'Technical Solutions Consultant (Healthcare IT)', 'applied', '2025-12-19', 'Randstad', ''),
('YOUR_USER_ID_HERE', 'Randstad', 'Data Analyst (Ecommerce/FMCG)', 'applied', '2025-12-19', 'Randstad', ''),
('YOUR_USER_ID_HERE', 'Randstad', 'IT & Automation Analyst (Asset Management)', 'applied', '2025-12-19', 'Randstad', ''),
('YOUR_USER_ID_HERE', 'Randstad', 'IT Implementation & Support (Medical Device)', 'applied', '2025-12-19', 'Randstad', ''),
('YOUR_USER_ID_HERE', 'Randstad', 'Cyber Threat Analyst', 'applied', '2025-12-19', 'Randstad', ''),
('YOUR_USER_ID_HERE', 'Randstad', 'Data & Operation Analyst (Python/SQL)', 'applied', '2025-12-19', 'Randstad', ''),
('YOUR_USER_ID_HERE', 'Randstad', 'Software Test/QA Engineer (Manual + Cloud)', 'applied', '2025-12-19', 'Randstad', ''),
('YOUR_USER_ID_HERE', 'Straits Financial Group', 'Business Analyst (1-yr Contract)', 'applied', '2025-12-18', 'LinkedIn', ''),
('YOUR_USER_ID_HERE', 'A-IT Software Services', '(role not specified)', 'applied', '2025-12-18', 'LinkedIn', ''),
('YOUR_USER_ID_HERE', 'Russell Tobin', 'Business Analyst', 'applied', '2025-12-21', 'LinkedIn', ''),
('YOUR_USER_ID_HERE', 'UOB', 'AI Data Analytics Programme 2026', 'rejected', '2025-12-17', 'Direct', 'Rejected 17 Dec 2025.'),
('YOUR_USER_ID_HERE', 'UOB', 'Technology Development Programme 2026', 'rejected', '2025-12-15', 'Direct', 'Rejected 15 Dec 2025.'),
('YOUR_USER_ID_HERE', 'DomainTools', 'Associate Solutions Engineer (APAC)', 'rejected', '2025-12-10', 'Direct', 'Rejected 10 Dec 2025.'),
('YOUR_USER_ID_HERE', 'Evooq', 'Application Support Engineer', 'rejected', '2025-12-10', 'Direct', 'Rejected 10 Dec 2025 (earlier application).'),
('YOUR_USER_ID_HERE', 'Synapxe', 'Business Analyst (Ariba/SAP)', 'rejected', '2025-12-07', 'Direct', 'Rejected 7 Dec 2025.'),
('YOUR_USER_ID_HERE', 'Synapxe', 'Data Analyst (Jan/Feb 2026 intake)', 'rejected', '2025-12-06', 'Direct', 'Rejected 6 Dec 2025.'),
('YOUR_USER_ID_HERE', 'Shopee', 'Business Intelligence Solution Analyst', 'applied', '2025-12-01', 'Direct', 'Application submitted 1 Dec 2025.'),
('YOUR_USER_ID_HERE', 'NUHS', 'Executive/Senior Executive, Artificial Intelligence', 'applied', '2025-11-30', 'Direct', ''),
('YOUR_USER_ID_HERE', 'NTU', 'Analyst Programmer / Systems Analyst (NIE)', 'applied', '2025-11-14', 'Direct', ''),
('YOUR_USER_ID_HERE', 'OpenAI', 'AI Support Engineer (Nov batch)', 'applied', '2025-11-14', 'Direct', 'Applied Nov 2025. Rejected Apr 2026.'),
('YOUR_USER_ID_HERE', 'Plusgrade', 'Web Integrator', 'rejected', '2025-10-28', 'Direct', 'Rejected 28 Oct 2025.'),
('YOUR_USER_ID_HERE', 'Mavericks Consulting', 'Full-Stack Developer', 'rejected', '2025-10-13', 'Direct', 'Rejected 13 Oct 2025.'),
('YOUR_USER_ID_HERE', 'Riot Games', 'Associate SWE - Live Site Reliability Engineering', 'applied', '2025-09-30', 'Direct', 'Application confirmation received.'),
('YOUR_USER_ID_HERE', 'Vanguard Software', 'Software Tester (Fresh Graduate/Junior)', 'applied', '2025-07-31', 'LinkedIn', '');
